import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import {
  VApp,
  VBtn,
  VTextField,
  VTextarea,
  VSelect,
  VCheckbox,
  VCheckboxBtn,
  VAlert,
  VChip,
  VDialog,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VTabs,
  VTab,
  VTable,
  VTooltip,
  VIcon,
  VDivider,
} from 'vuetify/components'

export default createVuetify({
  components: {
    VApp,
    VBtn,
    VTextField,
    VTextarea,
    VSelect,
    VCheckbox,
    VCheckboxBtn,
    VAlert,
    VChip,
    VDialog,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VTabs,
    VTab,
    VTable,
    VTooltip,
    VIcon,
    VDivider,
  },
  icons: { defaultSet: 'mdi', aliases, sets: { mdi } },
  theme: {
    defaultTheme: 'radioSender',
    themes: {
      radioSender: {
        dark: false,
        colors: {
          primary: '#0067c0',
          secondary: '#616161',
          background: '#f3f3f3',
          surface: '#ffffff',
          error: '#b3261e',
          warning: '#936300',
          success: '#2e7d32',
          info: '#0067c0',
          'on-background': '#262626',
          'on-surface': '#262626',
        },
      },
    },
  },
  defaults: {
    VBtn: { variant: 'outlined', size: 'small', rounded: 'sm' },
    VTextField: { variant: 'outlined', density: 'compact', hideDetails: 'auto', color: 'primary' },
    VTextarea: { variant: 'outlined', density: 'compact', hideDetails: 'auto', color: 'primary' },
    VSelect: { variant: 'outlined', density: 'compact', hideDetails: 'auto', color: 'primary' },
    VCheckbox: { density: 'compact', hideDetails: true, color: 'primary' },
    VTable: { density: 'compact' },
    VCard: { rounded: 'sm' },
    VChip: { size: 'small', variant: 'text', rounded: 'sm' },
    VAlert: { density: 'compact', variant: 'tonal', rounded: 'sm' },
  },
})
