import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import {
  VApp,
  VBtn,
  VTextField,
  VTextarea,
  VSelect,
  VSwitch,
  VCheckboxBtn,
  VAlert,
  VChip,
  VDialog,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VTabs,
  VTab,
  VTable,
  VTooltip,
  VIcon,
  VDivider,
} from 'vuetify/components'

export default createVuetify({
  components: {
    VApp,
    VBtn,
    VTextField,
    VTextarea,
    VSelect,
    VSwitch,
    VCheckboxBtn,
    VAlert,
    VChip,
    VDialog,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VTabs,
    VTab,
    VTable,
    VTooltip,
    VIcon,
    VDivider,
  },
  icons: { defaultSet: 'mdi', aliases, sets: { mdi } },
  theme: {
    defaultTheme: 'radioSender',
    themes: {
      radioSender: {
        dark: false,
        colors: {
          primary: '#13776e',
          secondary: '#243e52',
          background: '#f4f7fa',
          surface: '#ffffff',
          error: '#b13e4a',
          warning: '#a97425',
          success: '#26836c',
          info: '#47728d',
          'on-background': '#253b4a',
          'on-surface': '#253b4a',
        },
      },
    },
  },
  defaults: {
    VBtn: { variant: 'outlined', size: 'small', rounded: 'lg' },
    VTextField: { variant: 'outlined', density: 'compact', hideDetails: 'auto', color: 'primary' },
    VTextarea: { variant: 'outlined', density: 'compact', hideDetails: 'auto', color: 'primary' },
    VSelect: { variant: 'outlined', density: 'compact', hideDetails: 'auto', color: 'primary' },
    VSwitch: { density: 'compact', hideDetails: true, color: 'primary', inset: true },
    VTable: { density: 'compact' },
    VChip: { size: 'small', variant: 'tonal' },
    VAlert: { density: 'compact', variant: 'tonal', rounded: 'lg' },
  },
})
